server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: employee

  mail:
    host: smtp.gmail.com
    port: 587
    username: <your-email>
    password: <your-password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
